version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: pyside2
      version-update: semver-patch
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: daily
