language: python
python:
    - "3.6"
install:
    - "pip install pipenv"
    - "pipenv install --dev"
script: "coverage run --source=zero_play -m pytest"

after_success:
    - pip install codecov
    - codecov