language: python
python:
    - "3.8"
sudo: required
install:
    - sudo apt-get install libxcb-icccm4 libxcb-image0
    - "pip install pipenv"
    - "pipenv install --dev"
script:
    - mypy zero_play && QT_DEBUG_PLUGINS=1 coverage run --source=zero_play -m pytest -s
after_success:
    - pip install codecov
    - codecov