dist: bionic
language: python
python:
    - "3.8"
before_install:
    - "sudo apt-get install libxcb-xinerama0 libxkbcommon-x11-0 xserver-xephyr"
install:
    - "pip install pipenv"
    - "pipenv install --dev"
services:
    # XVirtual Frame Buffer creates a mock display for Qt tests.
    - xvfb
script:
    # Add QT_DEBUG_PLUGINS=1 before coverage to debug Qt library problems.
    - mypy zero_play && coverage run --source=zero_play -m pytest -s
after_success:
    - pip install codecov
    - codecov