# This workflow will install Python dependencies and run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install missing package and fake XServer
        run: |
          # Work around missing deps: https://bugreports.qt.io/browse/PYSIDE-1547
          sudo apt-get update
          sudo apt-get install -y -q freeglut3-dev xvfb libxkbcommon-x11-0 xserver-xephyr
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Test with pytest
        id: test
        run: |
          pipenv run mypy zero_play
          # Add QT_DEBUG_PLUGINS=1 before xvfb-run to debug Qt library problems.
          xvfb-run -a pipenv run coverage run --source=zero_play -m pytest
      - name: Upload code coverage
        run: |
          pipenv install codecov
          pipenv run codecov
      - name: Upload image diffs
        uses: actions/upload-artifact@v2
        if: ${{ always() && steps.test.outcome == 'failure' }}
        with:
          name: image-diffs
          path: |
            tests/pixmap_diffs/*.png
